### ISSUE TITLE
Empty folders in 1st release

### ISSUE THREAD

**Issue by 5T33Z0** [ClayMoreBoy/Hackintosh-Kext-Factory#1]
The following Folders contain no files:

- AMFIExemption
- ATH9KFixup
- DiskArbitrationFixup
- SystemProfilerMemoryFixup
- ThunderboltReset

**Comment by ClayMoreBoy** [comment]
> The following Folders contain no files:以下文件夹不包含文件：
> 
> * AMFIExemption AMFI豁免
> * ATH9KFixup ATH9K修复
> * DiskArbitrationFixup 磁盘仲裁修复
> * SystemProfilerMemoryFixup系统分析器内存修复
> * ThunderboltReset 雷电重置

The above software versions are not updated
